### ISSUE TITLE
CI for Nix

### ISSUE THREAD

**Issue by JosuGZ** [JosuGZ/razer-laptop-control#2]
There is currently an `install` job on the CI workflow. It runs the installation script and checks that the files are present.

It would be great to have an `install-nix` job.

**Comment by sebbelindholm** [comment]
Can probably look into it next week if you like I've never done anything like it with nix but doesn't sound that complicated from a single google search.

**Comment by JosuGZ** [comment]
Nice! It will be useful to prevent the build from breaking and as documentation.

I think that [this](https://github.com/JosuGZ/razer-laptop-control/blob/main/ci-helpers/check-installation.sh) script will only work partially as the names of the files are changed, but the part where it checks the binaries and that the service is enabled should be enough.
